
--roles
INSERT INTO ROLE(ID,ROLE_NAME,ROLE_DESCRIPTION) VALUES(1,'ADMIN','Admin Role');
INSERT INTO ROLE(ID,ROLE_NAME,ROLE_DESCRIPTION) VALUES(2,'EMPLOYEE','Employee Role');
INSERT INTO ROLE(ID,ROLE_NAME,ROLE_DESCRIPTION) VALUES(3,'CUSTOMER','Customer Role');
INSERT INTO ROLE(ID,ROLE_NAME,ROLE_DESCRIPTION) VALUES(4,'MASTER','Master/Dispatcher Role');


--accounts
/*password=password */
--employee_accounts
INSERT INTO USER_T(USERNAME,PASSWORD,ENABLED,CREDENTIALS_EXPIRED,EXPIRED,LOCKED)
VALUES ('adam_adamowicz','$2a$10$aiBgroa5UbCph3gb4WSiD.njeKqgsjXmHv/pbXiRVAYPMlewWDLD6',true,false,false,false);
INSERT INTO USER_T(USERNAME,PASSWORD,ENABLED,CREDENTIALS_EXPIRED,EXPIRED,LOCKED)
VALUES ('master','$2a$10$aiBgroa5UbCph3gb4WSiD.njeKqgsjXmHv/pbXiRVAYPMlewWDLD6',true,false,false,false);

--user details
INSERT INTO user_details(id, first_name, last_name, phone, email)
VALUES(1, 'Adam','Adamowicz','+48111222333','adamowicz@email.com');

INSERT INTO user_details(id, first_name, last_name, phone, email)
VALUES(2, 'Adam','Klient','+48123456789','klient1@mail.com');

--users
INSERT INTO USER_T(USERNAME,PASSWORD,ENABLED,CREDENTIALS_EXPIRED,EXPIRED,LOCKED,DTYPE, DETAILS_ID)
VALUES ('adam_adamowicz','$2a$10$aiBgroa5UbCph3gb4WSiD.njeKqgsjXmHv/pbXiRVAYPMlewWDLD6',true,false,false,false, 'EMPLOYEE', 1);

INSERT INTO USER_T(USERNAME,PASSWORD,ENABLED,CREDENTIALS_EXPIRED,EXPIRED,LOCKED,DTYPE, DETAILS_ID)
VALUES ('adam_klient','$2a$10$aiBgroa5UbCph3gb4WSiD.njeKqgsjXmHv/pbXiRVAYPMlewWDLD6',true,false,false,false,'CUSTOMER', 2);

--account_role
INSERT INTO USER_ROLE(USER_ID,ID) SELECT a.USER_ID,r.ID FROM USER_T a,ROLE r WHERE a.USERNAME='adam_adamowicz'
and r.ID=1;
INSERT INTO USER_ROLE(USER_ID,ID) SELECT a.USER_ID,r.ID FROM USER_T a,ROLE r WHERE a.USERNAME='adam_klient'
and r.ID=3;
INSERT INTO USER_ROLE(USER_ID,ID) SELECT a.USER_ID,r.ID FROM USER_T a,ROLE r WHERE a.USERNAME='master'
and r.ID=4;

--employees
INSERT INTO EMPLOYEE(FIRST_NAME,LAST_NAME,PHONE,EMAIL,USER_ID)
VALUES('Adam','Adamowicz','+48111222333','adamowicz@email.com',1);

--customers
INSERT INTO CUSTOMER(FIRST_NAME,LAST_NAME,PHONE,EMAIL,USER_ID)
VALUES('Adam','Klient','+48123456789','klient1@mail.com',3);

--master
INSERT INTO EMPLOYEE(FIRST_NAME,LAST_NAME,PHONE,EMAIL,USER_ID)
VALUES('Master','Master','+48341555999','master@email.com',2);

--devices
/*INSERT INTO DEVICE(ID,BRAND,MODEL,SERIAL_NUMBER,DESCRIPTION,EXTERNAL_ID)
VALUES(1,'SAMSUNG','ABC','0001234HUAHUA1234','Desc 1','#EXTERNALID9999345');
INSERT INTO DEVICE(ID,BRAND,MODEL,SERIAL_NUMBER,DESCRIPTION,EXTERNAL_ID)
VALUES(2,'LOGITECH','CCC','0007777LLAA5555','Desc 2','#EXTERNALID1114447');
INSERT INTO DEVICE(ID,BRAND,MODEL,SERIAL_NUMBER,DESCRIPTION,EXTERNAL_ID)
VALUES(3,'ASUS','DDDD','7424PINGPONG3787','Desc 3','#EXTERNALID777788*');*/
INSERT INTO USER_ROLE(USER_ID,ID) VALUES(1,1);
INSERT INTO USER_ROLE(USER_ID,ID) VALUES(2,3);